# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ca8f60e9378761caf39d54d6bee528e6b8dfb8aa133ef6111960e2b16098fcca0ccd023d4dcb26d24971575ac39d60ef13a17f371b050979ccace7f661d8267

test:
  secret_key_base: 9e85115ef4bff10d77bdb1ce3dc34ecd23373981f9c9ce48a65ec4146926fb737d1629866601d14e52700f84246d0d81f48ebc15b2b96d21888ad84cdb929ff8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
